services:
  postgres:
    image: postgres:16
    container_name: quark-postgres
    environment:
      POSTGRES_DB: quark_dev
      POSTGRES_USER: quark
      POSTGRES_PASSWORD: quarkpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: quark-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: quark-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

  nats:
    image: nats:2
    container_name: quark-nats
    ports:
      - "4222:4222"  # клиенты
      - "6222:6222"  # кластер
      - "8222:8222"  # мониторинг
    restart: unless-stopped

  auth-service:
    build: ./services/auth-service
    container_name: quark-auth
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://quark:quarkpass@postgres:5432/quark_dev
      - JWT_SECRET=1D4SqYIsrszmXpAH0/EhDzRjTemdL2BwWzzJNKTpzTQ=
    depends_on:
      - postgres
    restart: unless-stopped

  user-service:
    build: ./services/user-service
    container_name: quark-users
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgresql+asyncpg://quark:quarkpass@postgres:5432/quark_dev
      - JWT_SECRET=1D4SqYIsrszmXpAH0/EhDzRjTemdL2BwWzzJNKTpzTQ=
    depends_on:
      - postgres
      - auth-service
    restart: unless-stopped

  media-service:
    build: ./services/media-service
    ports:
      - "3003:3003"
    env_file:
      - ./services/media-service/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - minio
      - auth-service
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data: